[package]
name = "day_18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-macro = "0.2.0"
aoc_shared = { path = "../aoc_shared" }
